build_targets:
- commands:
  - chmod +x yourbased.sh
  - sh ./yourbased.sh
  container:
    image: yourbase/yb_ubuntu:16.04
  environment:
  - BUNDLE_GEMFILE=gemfiles/Gemfile-rails-5.1.x
  - SKIPPER_IGNORE="chmod +x yourbased.sh;sh ./yourbased.sh"
  name: 2.6.3_Gemfile-rails-5.1.x
- commands:
  - chmod +x yourbased.sh
  - sh ./yourbased.sh
  container:
    image: yourbase/yb_ubuntu:16.04
  environment:
  - BUNDLE_GEMFILE=gemfiles/Gemfile-rails-5.2.x
  - SKIPPER_IGNORE="chmod +x yourbased.sh;sh ./yourbased.sh"
  name: 2.6.3_Gemfile-rails-5.2.x
ci:
  builds:
  - build_target: 2.6.3_Gemfile-rails-5.1.x
    name: 2.6.3_Gemfile-rails-5.1.x
  - build_target: 2.6.3_Gemfile-rails-5.2.x
    name: 2.6.3_Gemfile-rails-5.2.x
dependencies:
  build:
  - ruby:2.6.3
